### ISSUE TITLE
Propozycja rzeczy kosmetycznej (do włączenia lub wyłączenia)

### ISSUE THREAD

**Issue by ReferTV** [michaljaz/itemszop#54]
![image](https://user-images.githubusercontent.com/61411400/159565905-0ba4e7a7-9fc3-43c2-b909-848396002901.png)
Dodanie efektu blur tła, podczas otwierania okienka z zakupem.

**Comment by ReferTV** [comment]
Najlepiej żeby wartości były konfigurowalne

**Comment by michaljaz** [comment]
dodane
