### ISSUE TITLE
Popup po użyciu Vouchera.

### ISSUE THREAD

**Issue by ReferTV** [michaljaz/itemszop#68]

**Comment by ReferTV** [comment]
![image](https://user-images.githubusercontent.com/61411400/178140888-6992185f-a29a-4b87-b32b-13e7ca37b58e.png)
ta wiadomość to według mnie za mało i jest słabo widoczna

**Comment by ReferTV** [comment]
nawet nie zauważyłem, że wyskoczyła

**Comment by michaljaz** [comment]
dobry pomysł
